import type { ReactNode } from "react"
import { Section } from "@/components/Section"

function Code({ children }: { children: ReactNode }) {
  return <code className="bg-muted rounded px-1 py-0.5 font-mono text-[0.85em]">{children}</code>
}

function Block({ title, children }: { title?: string; children: ReactNode }) {
  return (
    <div className="bg-card rounded-lg border p-5">
      {title ? <p className="mb-2 text-sm font-semibold">{title}</p> : null}
      <div className="text-muted-foreground space-y-3 text-sm leading-relaxed">{children}</div>
    </div>
  )
}

function Snippet({ children }: { children: string }) {
  return (
    <pre className="bg-muted overflow-x-auto rounded-md p-3 font-mono text-xs leading-relaxed">
      <code>{children}</code>
    </pre>
  )
}

export function Methodology() {
  return (
    <div className="space-y-14">
      <div>
        <p className="text-muted-foreground max-w-[68ch] leading-relaxed">
          Everything on the Results tab is generated by a single script, <Code>analysis/export_results.py</Code>,
          which reads the raw CSVs, runs every model, and writes the one JSON file the site reads. Nothing
          is computed in the browser and nothing is typed in by hand. This page walks through what that
          script actually does and why it&rsquo;s built the way it is, for anyone who wants to check the
          working rather than take the charts on faith.
        </p>
      </div>

      <Section
        id="how-pipeline"
        eyebrow="Pipeline"
        title="One script, one JSON file, checked at export time"
        lede={
          <>
            <Code>export_results.py</Code> imports the analysis modules, runs them against{" "}
            <Code>Data/*.csv</Code>, and writes <Code>web/src/data/results.json</Code>. The front end
            imports that file as a typed module (<Code>web/src/lib/data.ts</Code>) and never touches the
            CSVs or the Python code.
          </>
        }
      >
        <Block title="Self-checking, not just self-generating">
          <p>
            Before writing the file, the script re-derives the polynomial and exponential R² values and
            asserts they still match figures published in the original analysis (
            <Code>EXPECTED_POLYNOMIAL_R2</Code>, <Code>EXPECTED_EXPONENTIAL_R2</Code>). It also checks that
            the fortnightly normal-equation solve still agrees with a least-squares solve within a fixed
            bound. If a future change to the analysis code silently shifts what the site claims, the export
            fails loudly with <Code>SystemExit</Code> instead of quietly shipping a different number under
            the same headline.
          </p>
        </Block>
        <Block title="Rounding for reproducible diffs">
          <p>
            Every float in the payload is rounded to 8 significant figures before being written. The
            fortnightly cubic fit comes out of a badly conditioned normal equation (more on that below), so
            its raw tail digits track the BLAS build on the machine that ran the export rather than anything
            about the data. Rounding to a precision the conditioning analysis says is actually honest means
            re-running the export on a clean checkout produces a byte-identical file unless something real
            changed &mdash; a deliberate property, not an accident of floating point.
          </p>
        </Block>
      </Section>

      <Section
        id="how-models"
        eyebrow="Model 1"
        title="Polynomial regression, solved by explicit normal equations"
        lede={
          <>
            <Code>LinearRegression</Code>, <Code>QuadraticRegression</Code> and <Code>CubicRegression</Code>{" "}
            (in <Code>PolynomialRegression/</Code>) each build a design matrix and solve for coefficients by
            inverting the normal equation directly, rather than calling a library solver.
          </>
        }
      >
        <Block>
          <Snippet>{`X_design = [1, CO, CO^2, ..., CO^k]
coefficients = inv(X_design.T @ X_design) @ X_design.T @ y`}</Snippet>
          <p>
            This is deliberate: an off-the-shelf least-squares call would silently absorb the numerical
            trouble the cubic case runs into. Explicit inversion exposes it. All three classes share a{" "}
            <Code>PolynomialModel</Code> base (<Code>base_regression.py</Code>) that guards against calling{" "}
            <Code>predict()</Code> before <Code>fit()</Code> and provides the R² calculation, so the three
            models differ only in the degree of the design matrix.
          </p>
        </Block>
        <Block title="Why the cubic breaks down">
          <p>
            CO readings are on the order of 10³ µg/m³, so a cubic term is on the order of 10⁹ and the
            corresponding entry of X<sup>T</sup>X lands near 10²⁴ &mdash; against roughly 10¹⁶ of precision a
            double can carry. The condition number of X<sup>T</sup>X for each degree is computed directly (
            <Code>validation.conditioning</Code>) and exported alongside the fit, rather than left as an
            unstated assumption. The export step also cross-checks the inverted solution against{" "}
            <Code>numpy.linalg.lstsq</Code> on the same data and fails the build if they ever disagree by
            more than the stated bound &mdash; which is how the site can claim the cubic&rsquo;s R² is sound
            despite the alarming condition number.
          </p>
        </Block>
        <Block title="Root-finding for the inverse question">
          <p>
            &ldquo;What CO level gives PM2.5 = 15?&rdquo; means solving the fitted polynomial for CO rather
            than evaluating it, so <Code>predict_inverse()</Code> hands the equation to{" "}
            <Code>scipy.optimize.fsolve</Code>. For the quadratic and cubic models this call is made with{" "}
            <Code>full_output=True</Code>, and the solver&rsquo;s own convergence flag and message are kept
            on the model instance (<Code>inverse_converged</Code>, <Code>inverse_message</Code>) rather than
            discarded. When the cubic solver fails to converge and returns a negative concentration, the
            export step reports that flag and the residual at the returned point, so the front end can say
            plainly that the number is not a root rather than presenting it as a prediction.
          </p>
        </Block>
      </Section>

      <Section
        id="how-exponential"
        eyebrow="Model 2"
        title="Exponential regression per pollutant"
        lede={
          <>
            <Code>analysis/methods.py::exponential_fits</Code> fits PM2.5 = a·e<sup>b·x</sup> independently
            for each of six pollutants, after scaling every predictor to [0, 1] with a per-run{" "}
            <Code>MinMaxScaler</Code>.
          </>
        }
      >
        <Block>
          <p>
            Fitting is done with <Code>scipy.optimize.curve_fit</Code> (raised iteration cap,{" "}
            <Code>maxfev=10000</Code>, since the default budget is too small for some pollutants to
            converge). If a fit still fails to converge, that pollutant&rsquo;s entry is <Code>None</Code>{" "}
            rather than a fabricated fit &mdash; and the export step checks every expected pollutant against
            its published R² before writing the file, so a silent convergence failure cannot reach the site
            unnoticed.
          </p>
          <p>
            The sign of the fitted <Code>b</Code> is not a quality signal: an inversely correlated pollutant
            (ozone, here) is fit just as well by taking <Code>b</Code> negative. Fit quality tracks the
            strength of the underlying relationship, which is why R² and correlation are reported side by
            side rather than one standing in for the other.
          </p>
        </Block>
      </Section>

      <Section
        id="how-simpson"
        eyebrow="Model 3"
        title="Simpson's rule for cumulative exposure"
        lede={
          <>
            <Code>analysis/methods.py::simpsons_method</Code> implements the composite Simpson&rsquo;s rule
            by hand over monthly pollutant means, integrated across six intervals per year.
          </>
        }
      >
        <Block>
          <Snippet>{`h = (x[-1] - x[0]) / (n - 1)
integral = y[0] + y[-1] + Σ (4 if i odd else 2) * y[i]
result = (h / 3) * integral`}</Snippet>
          <p>
            The rule requires an odd number of points, so a year with an even number of monthly means gets
            its last value duplicated to force one &mdash; which double-weights that month, and is reported
            as a stated limitation rather than smoothed over. Partial years at the edges of the record
            (November&ndash;December 2020, January 2023) are interpolated onto the same six-interval axis as
            a full year via <Code>np.interp</Code>, so a two-month stub and a twelve-month year are
            integrated over identical x-ranges; the exported <Code>coverage</Code> block flags which years
            are complete so the front end can say so explicitly instead of implying every year is comparable.
          </p>
        </Block>
      </Section>

      <Section
        id="how-validation"
        eyebrow="Validation"
        title="Why the headline finding is cross-validation, not in-sample R²"
        lede="analysis/validation.py exists because in-sample R² cannot fall when a term is added, which makes it useless for choosing between the three polynomial degrees."
      >
        <Block title="Repeated k-fold cross-validation">
          <p>
            A single 5-fold split (<Code>random_state=0</Code>) happens to favour the linear model more than
            a typical split does, so the headline comparison is instead the mean over 200 independently
            reseeded 5-fold splits (<Code>repeated_cv</Code>), reported with its spread (mean, standard
            deviation, 5th/95th percentile) rather than a single point estimate. The claim on the site is
            about the ordering being stable across reseeds, not about any single decimal figure.
          </p>
        </Block>
        <Block title="Testing the averaging hypothesis directly">
          <p>
            <Code>aggregation_placebo</Code> exists to test, rather than assert, why fitting fortnightly
            means scores higher than fitting raw hourly rows. It re-bins the same hourly rows into random
            groups of the identical sizes as the real fortnights, refits, and repeats that 200 times. If
            averaging itself &mdash; removing noise &mdash; were the explanation, the random-bin R² would
            rise to match the fortnightly figure; instead it lands back at the hourly value, which is the
            evidence used on the site for &ldquo;this is aggregation over time structure, not noise
            removal.&rdquo;
          </p>
        </Block>
      </Section>

      <Section
        id="how-aqi"
        eyebrow="AQI"
        title="One breakpoint table, computed once"
        lede={
          <>
            <Code>analysis/aqi.py</Code> implements the US EPA index (2024 revision) as piecewise-linear
            interpolation over published concentration breakpoints, and every AQI-derived figure on the site
            &mdash; category counts, the timeline&rsquo;s shaded bands, monthly categories &mdash; is
            computed from that one module.
          </>
        }
      >
        <Block>
          <p>
            The concentration breakpoints and the AQI-value category bands are both defined once in Python (
            <Code>PM25_BREAKPOINTS</Code>, <Code>CATEGORIES</Code>) and exported into{" "}
            <Code>results.json</Code> as <Code>pm25_breakpoints</Code> and <Code>aqi_categories</Code>. The
            front end reads both rather than keeping its own copy of the EPA table, so a future revision to
            the breakpoints only has to change in one place to show up correctly everywhere it&rsquo;s used.
          </p>
        </Block>
      </Section>

      <Section id="how-frontend" eyebrow="Front end" title="A static site over one typed JSON file">
        <Block>
          <p>
            The site is a Vite + React + TypeScript build with no backend and no client-side computation:
            every number shown is already in <Code>results.json</Code> at build time. The shape of that file
            is described once as a TypeScript type (<Code>web/src/lib/data.ts</Code>), so a field the export
            script stops writing, or renames, shows up as a type error at build time rather than a runtime
            crash. Charts are built on Recharts; the design tokens and light/dark themes are plain CSS
            variables switched by a class on the root element.
          </p>
        </Block>
      </Section>
    </div>
  )
}
